# Generated by Django 3.2.16 on 2022-11-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useRedis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
